apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-hello-ing
spec:
  ingressClassName: nginx
  rules:
    - host: nginx-hello.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-hello-svc
                port:
                  number: 80
