apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello
spec:
  template:
    spec:
      containers:
        - name: server
          imagePullPolicy: Never
          image: docker.io/library/nginx-myhello:latest
